import React, { useEffect, useState } from 'react';

import '../styles/globals.css';
import Head from 'next/head';
import { QueryClientProvider, QueryClient } from 'react-query';
import { Provider } from 'react-redux';
import { store } from '@/utils/redux/store';
// import MainLayout from '@/components/Layout/Layout';

// create a client
const queryClient = new QueryClient();

export default function App({ Component, pageProps }) {
  // create a client
  // const [queryClient] = useState(() => new QueryClient());
  const [showing, setShowing] = useState(false);

  useEffect(() => {
    setShowing(true);
  }, []);

  if (!showing) {
    return null;
  }

  if (typeof window === 'undefined') {
    return <></>;
  } else {
    return (
      <>
        <Head>
          <title>Simple CRUD App</title>
          <meta content="width=device-width, initial-scale=1" name="viewport" />
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <QueryClientProvider client={queryClient} contextSharing={true}>
          <Provider store={store}>
            {/* <MainLayout> */}
            <Component {...pageProps} />
            {/* </MainLayout> */}
          </Provider>
        </QueryClientProvider>
      </>
    );
  }
}
